server:
  port: 8080

#thymelea configure
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    #Hot deployment file, page does not generate cache, timely update
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
    static-locations: classpath:/static
  mvc:
    static-path-pattern: /static/**